### ISSUE TITLE
Add `with_universe`

### ISSUE THREAD

**Issue by niklasdewally** [conjure-cp/uniplate#31]

**Comment by ozgurakgun** [comment]
What would this do then? Reconstructing the universe to make a new objects sounds like an overkill at first thought.

**Comment by niklasdewally** [comment]
> What would this do then? Reconstructing the universe to make a new object sounds like an overkill at first thought.

I don't know, however iterating over the universe of an expression is kind of useless without it....

**Comment by niklasdewally** [comment]
In particular, in the naive rewriter I am writing, I am needing to modify the universe...

**Comment by ozgurakgun** [comment]
but you cannot just update a thing in that list and give it back to with_universe. you would have to update it's children too.

**Comment by niklasdewally** [comment]
Would `contexts` work here:

https://hackage.haskell.org/package/uniplate-1.6.13/docs/Data-Generics-Uniplate-Operations.html#v:contexts

**Comment by niklasdewally** [comment]
> you are dangerously close to zippers :)

 always have been :)(holes is just a wrapper for `.uniplate()`)
